(ns euler.p002)

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By the terms in the Fibonacci sequence whose values do not exceed four million,
;; find the sum of the even-valued terms.

(defn fibo [n]
  (loop [n-2 1
         n-1 2
         acc [1 2]]
    (if (> n-2 n)
      acc
      (recur n-1 (+ n-2 n-1) (conj acc (+ n-2 n-1))))))

(reduce + (filter even? (drop-last 2 (fibo 4000000))))
