(ns problem-001
  (:import [java.lang Math]))

;; If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
;; Find the sum of all the multiples of 3 or 5 below 1000.

(- (reduce + (flatten (list (range 0 1000 3 ) (range 0 1000 5)))) (reduce + (range 0 1000 (* 3 5))))

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fibo [n]
  (loop [n-2 1 n-1 2 acc [1 2]]
    (if (> n-2 n)
      acc
      (recur n-1 (+ n-2 n-1) (conj acc (+ n-2 n-1))))))

(reduce + (filter even? (drop-last 2 (fibo 4000000))))

;;The prime factors of 13195 are 5, 7, 13 and 29.
;;What is the largest prime factor of the number 600851475143 ?

(defn prime [n]
  (let [sq (Math/sqrt n)]
  (loop [m 1 max 0]
    (if (= m n)
      max
      (recur (inc m) (if (= 0 (mod n m)) m max))))
  ))

;;(prime 600851475143)

(Math/sqrt 16)

;; prob 5
;; 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
;; What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?


(defn primes [n] 
  (loop [m 2 res []]
    (if (= m n)
      res
      (recur (inc m) (if (not-any? #(= 0 (mod m %1)) res) (conj res m) res)))))

(reduce * (flatten (distinct (map primes (range 3 10)))))
